### ISSUE TITLE
i can't do cordova platform add ios, works good in android

### ISSUE THREAD

**Issue by DiegoRodriguez93** [voxeet/voxeet-cordova-sample#1]
`PS C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master> cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms\ios
        Package: com.voxeet.cordova.sample
        Name: HelloWorld
iOS project created with cordova-ios@4.5.5
Installing "cordova-plugin-voxeet" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-voxeet': CordovaError: Uh oh!
Cannot find framework "C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master\plugins\cordova-plugin-voxeet\src\ios\Carthage\Build\iOS\VoxeetConferenceKit.framework" for plugin cordova-plugin-voxeet in iOS platform
    at install (C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master\platforms\ios\cordova\lib\plugman\pluginHandlers.js:109:48)
    at ActionStack.process (C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master\platforms\ios\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master\platforms\ios\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master\platforms\ios\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at Api.addPlugin (C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master\platforms\ios\cordova\Api.js:234:10)
    at handleInstall (C:\Users\Sistemas06\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\Sistemas06\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\Sistemas06\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:854:54)
    at C:\Users\Sistemas06\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\Sistemas06\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:13)
Uh oh!
Cannot find framework "C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master\plugins\cordova-plugin-voxeet\src\ios\Carthage\Build\iOS\VoxeetConferenceKit.framework" for plugin cordova-plugin-voxeet in iOS platform
PS C:\Users\Sistemas06\Desktop\cordova\voxeet-cordova-sample-master>`

**Comment by codlab** [comment]
Unfortunately, you can not add any iOS related elements using your project. You must be on a Mac OS to do anything related to iOS (it's not specific to the cordova but react native, unity, etc...).

**Comment by DiegoRodriguez93** [comment]
![20191018_152032](https://user-images.githubusercontent.com/40219882/67118372-239a3d80-f1bb-11e9-9372-822dc8368ce9.jpg)
same error in mac

**Comment by codlab** [comment]
You don't have carthage as the error log is telling you. Please take about the fact that both errors are not the same (the original one and the photo one).

For any future issue different than this, please open a new issue and avoid answering in closed ones.
